# Generated by Django 3.2.13 on 2022-07-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recette',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.categorie'),
        ),
    ]
